python predict.py -c rsna_3d_seg_resnet18 -f 0
python predict.py -c rsna_3d_seg_resnet18 -f 1
python predict.py -c rsna_3d_seg_resnet18 -f 2
python predict.py -c rsna_3d_seg_resnet18 -f 3
python predict.py -c rsna_3d_seg_resnet18 -f 4
python predict.py -c rsna_3d_seg_resnet50 -f 0
python predict.py -c rsna_3d_seg_resnet50 -f 1
python predict.py -c rsna_3d_seg_resnet50 -f 2
python predict.py -c rsna_3d_seg_resnet50 -f 3
python predict.py -c rsna_3d_seg_resnet50 -f 4
